### ISSUE TITLE
如果是在ListView中，将视图滚动出屏幕一半之外，显示会有问题

### ISSUE THREAD

**Issue by helengray** [wl9739/UITransitionDemo#1]

**Comment by eateeer** [comment]
谢谢反馈，你说的问题不知道是不是视图复用的原因。由于此项目只是一个 Demo 演示的作用，如果是只在 ListView 出现这个问题的话，抱歉我可能不会针对性地去排查这个问题。

如果你有相关的解决方案的话，欢迎 PR。
